#!/bin/sh

set -e

DST_DIR="/";
ROOT_DIR="/opt/dadd"
BKP_DIR="${ROOT_DIR}/__bkp"
DADD_DIR="${ROOT_DIR}/dd"
FILES="/usr/share/themes/base/meegotouch/sysuid/style/statusarea.css /usr/share/themes/base/meegotouch/libmeegotouchhome/style/libmeegotouchviews-modified-default.css /usr/share/themes/blanco/meegotouch/constants.ini /usr/share/themes/base/meegotouch/images/dadd-landscape.png /usr/share/themes/base/meegotouch/images/dadd-portrait.png /usr/share/themes/blanco/meegotouch/images/backgrounds/meegotouch-desktop-bg.png ";
XSESSION="mthome sysuid";
_______________________________________________="-----------------------------------------------";

if [ "$1" = "configure" ]; then

	if [ -d ${BKP_DIR} ]; then
		echo "Original theme files has backup! exit...";
		exit 0;
	fi

	echo "Backup original theme files...";
	TCH="mkdir -p ${BKP_DIR}";
	echo ${TSH}; ${TSH};
	echo ${_______________________________________________};

	for i in ${FILES}
	do
		if [ -f ${DST_DIR}/$i ]; then
			echo "Backup file -> ${DST_DIR}/$i to ${BKP_DIR}";
			TDIR=${BKP_DIR}/`dirname $i`;
			if [ ! -d ${TDIR} ]; then
				TSH="mkdir -p ${TDIR}";
				echo ${TSH}; ${TSH};
			fi
			TSH="cp -f ${DST_DIR}/$i ${BKP_DIR}/$i";
			echo ${TSH}; ${TSH};
			echo "";
		fi
	done

	echo "Original theme files backup finished.";
	echo ${_______________________________________________};
	echo "Cover dadd theme files..."

	for i in ${FILES}
	do
		if [ -f ${DST_DIR}/$i ]; then
			echo "Cover file -> ${DADD_DIR}/$i to ${DST_DIR}";
		fi
		TDIR=${DST_DIR}/`dirname $i`;
		if [ ! -d ${TDIR} ]; then
			TSH="mkdir -p ${TDIR}";
			echo ${TSH}; ${TSH};
		fi
		TSH="cp -f ${DADD_DIR}/$i ${DST_DIR}/$i";
		echo ${TSH}; ${TSH};
		echo "";
	done

	echo "dadd theme install finished.";
	echo ${_______________________________________________};

	if [ "x" = "x0" ]; then
		echo "Restart X session...";

		for i in ${XSESSION}
		do
			TSH="initctl restart xsession/$i";
			echo ${TSH}; ${TSH};
		done

		echo "Restart X session finished.";
		echo ${_______________________________________________};
	fi

	exit 0;
fi
